// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeVuw-xmgbFPgAiSrs21m4m8gL6o3NUaM',
    appId: '1:669650484005:web:cdb00f285d4aabcfce78cc',
    messagingSenderId: '669650484005',
    projectId: 'seguridadtrujillo-b3a7c',
    authDomain: 'seguridadtrujillo-b3a7c.firebaseapp.com',
    storageBucket: 'seguridadtrujillo-b3a7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB38HKI89GL6lhDRdOSG329MDm6-pNeQBs',
    appId: '1:669650484005:android:fad836eec36a5fbbce78cc',
    messagingSenderId: '669650484005',
    projectId: 'seguridadtrujillo-b3a7c',
    storageBucket: 'seguridadtrujillo-b3a7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjvv7xazUYvHiuTyW1O77gPT8uy6hC32I',
    appId: '1:669650484005:ios:0d310f8f87d9cb90ce78cc',
    messagingSenderId: '669650484005',
    projectId: 'seguridadtrujillo-b3a7c',
    storageBucket: 'seguridadtrujillo-b3a7c.appspot.com',
    iosClientId: '669650484005-dms1epe5fgs1295678t34a42kvd46frf.apps.googleusercontent.com',
    iosBundleId: 'com.example.maps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjvv7xazUYvHiuTyW1O77gPT8uy6hC32I',
    appId: '1:669650484005:ios:0d310f8f87d9cb90ce78cc',
    messagingSenderId: '669650484005',
    projectId: 'seguridadtrujillo-b3a7c',
    storageBucket: 'seguridadtrujillo-b3a7c.appspot.com',
    iosClientId: '669650484005-dms1epe5fgs1295678t34a42kvd46frf.apps.googleusercontent.com',
    iosBundleId: 'com.example.maps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeVuw-xmgbFPgAiSrs21m4m8gL6o3NUaM',
    appId: '1:669650484005:web:27963ac02e814842ce78cc',
    messagingSenderId: '669650484005',
    projectId: 'seguridadtrujillo-b3a7c',
    authDomain: 'seguridadtrujillo-b3a7c.firebaseapp.com',
    storageBucket: 'seguridadtrujillo-b3a7c.appspot.com',
  );
}
